[build]
  publish = ".next"
  command = "npm run build"

[build.environment]
  NEXT_PUBLIC_API_URL = "https://hackx-2.onrender.com"
  NODE_VERSION = "18"

[[redirects]]
  from = "/_next/*"
  to = "/_next/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
